/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rayhealthcare.omni.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.rayhealthcare.omni.model.Consulta;
import com.rayhealthcare.omni.model.ConsultaModel;
import com.rayhealthcare.omni.model.ConsultaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Consulta service. Represents a row in the &quot;FOO_Consulta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ConsultaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsultaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsultaImpl
 * @see Consulta
 * @see ConsultaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ConsultaModelImpl extends BaseModelImpl<Consulta>
	implements ConsultaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consulta model instance should use the {@link Consulta} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Consulta";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "consultaId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "pacienteId", Types.BIGINT },
			{ "medicoId", Types.BIGINT },
			{ "especialidade", Types.VARCHAR },
			{ "time_", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("consultaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("pacienteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("medicoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("especialidade", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("time_", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_Consulta (uuid_ VARCHAR(75) null,consultaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,pacienteId LONG,medicoId LONG,especialidade VARCHAR(75) null,time_ LONG)";
	public static final String TABLE_SQL_DROP = "drop table FOO_Consulta";
	public static final String ORDER_BY_JPQL = " ORDER BY consulta.time DESC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_Consulta.time_ DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.rayhealthcare.omni.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rayhealthcare.omni.model.Consulta"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.rayhealthcare.omni.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rayhealthcare.omni.model.Consulta"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.rayhealthcare.omni.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rayhealthcare.omni.model.Consulta"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long PACIENTEID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long TIME_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Consulta toModel(ConsultaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Consulta model = new ConsultaImpl();

		model.setUuid(soapModel.getUuid());
		model.setConsultaId(soapModel.getConsultaId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPacienteId(soapModel.getPacienteId());
		model.setMedicoId(soapModel.getMedicoId());
		model.setEspecialidade(soapModel.getEspecialidade());
		model.setTime(soapModel.getTime());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Consulta> toModels(ConsultaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Consulta> models = new ArrayList<Consulta>(soapModels.length);

		for (ConsultaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.rayhealthcare.omni.service.util.ServiceProps.get(
				"lock.expiration.time.com.rayhealthcare.omni.model.Consulta"));

	public ConsultaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _consultaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConsultaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _consultaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Consulta.class;
	}

	@Override
	public String getModelClassName() {
		return Consulta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("consultaId", getConsultaId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("pacienteId", getPacienteId());
		attributes.put("medicoId", getMedicoId());
		attributes.put("especialidade", getEspecialidade());
		attributes.put("time", getTime());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long consultaId = (Long)attributes.get("consultaId");

		if (consultaId != null) {
			setConsultaId(consultaId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long pacienteId = (Long)attributes.get("pacienteId");

		if (pacienteId != null) {
			setPacienteId(pacienteId);
		}

		Long medicoId = (Long)attributes.get("medicoId");

		if (medicoId != null) {
			setMedicoId(medicoId);
		}

		String especialidade = (String)attributes.get("especialidade");

		if (especialidade != null) {
			setEspecialidade(especialidade);
		}

		Long time = (Long)attributes.get("time");

		if (time != null) {
			setTime(time);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getConsultaId() {
		return _consultaId;
	}

	@Override
	public void setConsultaId(long consultaId) {
		_consultaId = consultaId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPacienteId() {
		return _pacienteId;
	}

	@Override
	public void setPacienteId(long pacienteId) {
		_columnBitmask |= PACIENTEID_COLUMN_BITMASK;

		if (!_setOriginalPacienteId) {
			_setOriginalPacienteId = true;

			_originalPacienteId = _pacienteId;
		}

		_pacienteId = pacienteId;
	}

	public long getOriginalPacienteId() {
		return _originalPacienteId;
	}

	@JSON
	@Override
	public long getMedicoId() {
		return _medicoId;
	}

	@Override
	public void setMedicoId(long medicoId) {
		_medicoId = medicoId;
	}

	@JSON
	@Override
	public String getEspecialidade() {
		if (_especialidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _especialidade;
		}
	}

	@Override
	public void setEspecialidade(String especialidade) {
		_especialidade = especialidade;
	}

	@JSON
	@Override
	public long getTime() {
		return _time;
	}

	@Override
	public void setTime(long time) {
		_columnBitmask = -1L;

		_time = time;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Consulta.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Consulta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Consulta toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Consulta)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConsultaImpl consultaImpl = new ConsultaImpl();

		consultaImpl.setUuid(getUuid());
		consultaImpl.setConsultaId(getConsultaId());
		consultaImpl.setGroupId(getGroupId());
		consultaImpl.setCompanyId(getCompanyId());
		consultaImpl.setUserId(getUserId());
		consultaImpl.setUserName(getUserName());
		consultaImpl.setCreateDate(getCreateDate());
		consultaImpl.setModifiedDate(getModifiedDate());
		consultaImpl.setPacienteId(getPacienteId());
		consultaImpl.setMedicoId(getMedicoId());
		consultaImpl.setEspecialidade(getEspecialidade());
		consultaImpl.setTime(getTime());

		consultaImpl.resetOriginalValues();

		return consultaImpl;
	}

	@Override
	public int compareTo(Consulta consulta) {
		int value = 0;

		if (getTime() < consulta.getTime()) {
			value = -1;
		}
		else if (getTime() > consulta.getTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Consulta)) {
			return false;
		}

		Consulta consulta = (Consulta)obj;

		long primaryKey = consulta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ConsultaModelImpl consultaModelImpl = this;

		consultaModelImpl._originalUuid = consultaModelImpl._uuid;

		consultaModelImpl._originalGroupId = consultaModelImpl._groupId;

		consultaModelImpl._setOriginalGroupId = false;

		consultaModelImpl._originalCompanyId = consultaModelImpl._companyId;

		consultaModelImpl._setOriginalCompanyId = false;

		consultaModelImpl._setModifiedDate = false;

		consultaModelImpl._originalPacienteId = consultaModelImpl._pacienteId;

		consultaModelImpl._setOriginalPacienteId = false;

		consultaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Consulta> toCacheModel() {
		ConsultaCacheModel consultaCacheModel = new ConsultaCacheModel();

		consultaCacheModel.uuid = getUuid();

		String uuid = consultaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			consultaCacheModel.uuid = null;
		}

		consultaCacheModel.consultaId = getConsultaId();

		consultaCacheModel.groupId = getGroupId();

		consultaCacheModel.companyId = getCompanyId();

		consultaCacheModel.userId = getUserId();

		consultaCacheModel.userName = getUserName();

		String userName = consultaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			consultaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			consultaCacheModel.createDate = createDate.getTime();
		}
		else {
			consultaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			consultaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			consultaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		consultaCacheModel.pacienteId = getPacienteId();

		consultaCacheModel.medicoId = getMedicoId();

		consultaCacheModel.especialidade = getEspecialidade();

		String especialidade = consultaCacheModel.especialidade;

		if ((especialidade != null) && (especialidade.length() == 0)) {
			consultaCacheModel.especialidade = null;
		}

		consultaCacheModel.time = getTime();

		return consultaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", consultaId=");
		sb.append(getConsultaId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", pacienteId=");
		sb.append(getPacienteId());
		sb.append(", medicoId=");
		sb.append(getMedicoId());
		sb.append(", especialidade=");
		sb.append(getEspecialidade());
		sb.append(", time=");
		sb.append(getTime());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.rayhealthcare.omni.model.Consulta");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>consultaId</column-name><column-value><![CDATA[");
		sb.append(getConsultaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pacienteId</column-name><column-value><![CDATA[");
		sb.append(getPacienteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>medicoId</column-name><column-value><![CDATA[");
		sb.append(getMedicoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>especialidade</column-name><column-value><![CDATA[");
		sb.append(getEspecialidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>time</column-name><column-value><![CDATA[");
		sb.append(getTime());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Consulta.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Consulta.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _consultaId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _pacienteId;
	private long _originalPacienteId;
	private boolean _setOriginalPacienteId;
	private long _medicoId;
	private String _especialidade;
	private long _time;
	private long _columnBitmask;
	private Consulta _escapedModel;
}