/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rayhealthcare.omni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Consulta service. Represents a row in the &quot;FOO_Consulta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rayhealthcare.omni.model.impl.ConsultaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rayhealthcare.omni.model.impl.ConsultaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Consulta
 * @see com.rayhealthcare.omni.model.impl.ConsultaImpl
 * @see com.rayhealthcare.omni.model.impl.ConsultaModelImpl
 * @generated
 */
@ProviderType
public interface ConsultaModel extends BaseModel<Consulta>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a consulta model instance should use the {@link Consulta} interface instead.
	 */

	/**
	 * Returns the primary key of this consulta.
	 *
	 * @return the primary key of this consulta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this consulta.
	 *
	 * @param primaryKey the primary key of this consulta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this consulta.
	 *
	 * @return the uuid of this consulta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this consulta.
	 *
	 * @param uuid the uuid of this consulta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the consulta ID of this consulta.
	 *
	 * @return the consulta ID of this consulta
	 */
	public long getConsultaId();

	/**
	 * Sets the consulta ID of this consulta.
	 *
	 * @param consultaId the consulta ID of this consulta
	 */
	public void setConsultaId(long consultaId);

	/**
	 * Returns the group ID of this consulta.
	 *
	 * @return the group ID of this consulta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this consulta.
	 *
	 * @param groupId the group ID of this consulta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this consulta.
	 *
	 * @return the company ID of this consulta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this consulta.
	 *
	 * @param companyId the company ID of this consulta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this consulta.
	 *
	 * @return the user ID of this consulta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this consulta.
	 *
	 * @param userId the user ID of this consulta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this consulta.
	 *
	 * @return the user uuid of this consulta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this consulta.
	 *
	 * @param userUuid the user uuid of this consulta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this consulta.
	 *
	 * @return the user name of this consulta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this consulta.
	 *
	 * @param userName the user name of this consulta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this consulta.
	 *
	 * @return the create date of this consulta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this consulta.
	 *
	 * @param createDate the create date of this consulta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this consulta.
	 *
	 * @return the modified date of this consulta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this consulta.
	 *
	 * @param modifiedDate the modified date of this consulta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the paciente ID of this consulta.
	 *
	 * @return the paciente ID of this consulta
	 */
	public long getPacienteId();

	/**
	 * Sets the paciente ID of this consulta.
	 *
	 * @param pacienteId the paciente ID of this consulta
	 */
	public void setPacienteId(long pacienteId);

	/**
	 * Returns the medico ID of this consulta.
	 *
	 * @return the medico ID of this consulta
	 */
	public long getMedicoId();

	/**
	 * Sets the medico ID of this consulta.
	 *
	 * @param medicoId the medico ID of this consulta
	 */
	public void setMedicoId(long medicoId);

	/**
	 * Returns the especialidade of this consulta.
	 *
	 * @return the especialidade of this consulta
	 */
	@AutoEscape
	public String getEspecialidade();

	/**
	 * Sets the especialidade of this consulta.
	 *
	 * @param especialidade the especialidade of this consulta
	 */
	public void setEspecialidade(String especialidade);

	/**
	 * Returns the time of this consulta.
	 *
	 * @return the time of this consulta
	 */
	public long getTime();

	/**
	 * Sets the time of this consulta.
	 *
	 * @param time the time of this consulta
	 */
	public void setTime(long time);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Consulta consulta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Consulta> toCacheModel();

	@Override
	public Consulta toEscapedModel();

	@Override
	public Consulta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}